title: Conference Deadlines # (Maintained by @cassens)
# email: github@cassens.org
description: Countdowns to top AI, HCI, SFL, Ambient Systems, Context conference deadlines
author: Joerg Cassens

domain: "conferences.kriwi.de"
baseurl: ""

twitter_username: cassens
twitter_hashtag: context
github_username: cassens
github_repo: conferences

markdown: kramdown
ga_id: UA-36274081-2
