title: Conference Deadlines
#email: conferences@kriwi.de
description: Deadlines for conferences in AI, HCI, Multimodality, Linguistics, Cognition, and Behavioural Interfaces. 
author: Joerg Cassens

domain: "conferences.kriwi.de"
baseurl: ""

twitter_username: cassens
twitter_hashtag: conferences
github_username: cassens
github_repo: conferences

markdown: kramdown
